name: EtriaBending
version: 1.0
main: com.etriacraft.etriabending.EtriaBending
depends: [GriefPrevention]
commands:
  clear:
  copyinv:
  item:
    aliases: [i]
  iteminfo:
  motd:
  message:
    aliases: [pm,whisper,tell,message]
  reply:
    aliases: [r]
  modchat:
    aliases: [mc,ac,adminchat]
  ignore:
  ignorelist:
  gamemode:
    aliases: [gm]
  getpos:
  god:
  hat:
  help:
  vanish:
  workbench:
    aliases: [wb]
  enchantingtable:
    aliases: [et]
  displayname:
    aliases: [nick,dn]
  eb:
  maintenance:
  trade:
  spawn:
  tpa:
  tp:
  tphere:
  chunkfix:
  setspawn:
  spawnmob:
  weather:
permissions:
  eb.admin:
    default: false
    children:
      eb.clear: true
      eb.clear.other: true
      eb.copyinv: true
      eb.item: true
      eb.iteminfo: true
      eb.motd: true
      eb.msg: true
      eb.reply: true
      eb.msg.spy: true
      eb.modchat: true
      eb.ignore.use: true
      eb.ignore.bypass: true
      eb.gamemode: true
      eb.gamemode.other: true
      eb.getpos: true
      eb.god.other: true
      eb.god: true
      eb.hat: true
      eb.help: true
      eb.vanish: true
      eb.vanish.alert: true
      eb.workbench: true
      eb.enchantingtable: true
      eb.displayname: true
      eb.displayname.other: true
      eb.eb: true
      eb.maintenance: true
      eb.maintenance.safe: true
      eb.trade: true
      eb.spawn: true
      eb.tpa.answer: true
      eb.tp: true
      eb.tphere: true
      eb.chunkfix: true
      eb.setspawn: true
      eb.spawnmob: true
      eb.weather: true
      eb.vanish.seehidden: true
      eb.loginlimit.bypass: true
      eb.savexp: true